#!/bin/bash
export ZFLIST_HUB_TOKEN=$INPUT_TOKEN
export ZFLIST_HUB_USER=$INPUT_USER

filename=$(echo "$INPUT_NAME" | sed 's#refs/tags/##g')
action=${INPUT_ACTION^^}

if [ "$action" == "PUBLISH" ]; then
    echo "Initializing new flist"
    zflist init

    echo "Building the flist (path: $INPUT_ROOT)"
    zflist putdir $INPUT_ROOT /
    zflist commit /tmp/$filename

    echo "Uploading to the hub"
    zflist hub upload /tmp/$filename
fi

if [ "$action" == "SYMLINK" ]; then
    echo "Symlinking $filename -> $INPUT_TARGET"
    zflist hub symlink $filename $INPUT_TARGET
fi

if [ "$action" == "PROMOTE" ]; then
    echo "Promoting $filename -> $INPUT_TARGET"
    zflist hub promote $filename $INPUT_TARGET
fi
